version: '3'

networks:
  app-tier:
    driver: bridge

services:
  mini-quiz-app:
    build: .
    ports: 
      - "3001:3001"
    volumes: 
      - .:/usr/src/app
    networks:
      - app-tier
    depends_on:
      - pgsqldb
  pgsqldb:
    image: postgres:12
    ports: 
      - "5432:5432"
    networks:
      - app-tier
    env_file:
      - .env
    environment:
      - POSTGRES_USER
      - POSTGRES_DB
      - POSTGRES_HOST
      - POSTGRES_PASSWORD
    volumes:
      - ./postgres/-data:/var/lib/postgresql/data